name: iumrah_project
description: iUmrah Project
publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.6
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  
  path_provider: ^2.1.2
  photo_manager: ^3.0.0
  in_app_purchase: ^3.2.0
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^8.1.2
  share_plus: ^8.0.2
  

  video_player: ^2.9.1
  connectivity_plus: ^4.0.1
  just_audio: ^0.9.36
  siri_wave: ^2.3.0
  audio_visualizer: ^1.0.1
  audioplayers: ^5.2.1
  dio: ^5.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/video/reg_video.mp4
    - assets/video/advisor_video.mp4


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700

flutter_native_splash:

  android: true
  ios: true

  color: "#FFFFFF"

  android_12:
   
    icon_background_color: "#FFFFFF"

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/icon.png